# Use the official Node.js 18 image as a parent image
FROM node:18

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install all dependencies defined in the package.json
RUN yarn install

# Copy all files from your host to your image filesystem at /app
COPY . .
COPY .env.local ./.env.production.local

# Build the application
RUN yarn build

# Informs Docker that the container listens on the specified network port at runtime
EXPOSE 3000

# Provides the default command to execute when the container starts
CMD ["yarn", "start"]