apiVersion: v1
kind: Service
metadata:
  name: peerprep-user
  annotations:
      cloud.google.com/network-tier: Standard
spec:
  selector:
    app: peerprep-user
  ports:
  - protocol: TCP
    port: 8001
  type: LoadBalancer
  loadBalancerIP: 35.213.173.19

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: peerprep-user
  template:
    metadata:
      labels:
        app: peerprep-user
    spec:
      containers:
      - name: peerprep-user
        image: deployment87/dply87:peerprep-user
        env:
        - name: PSQL_DATABASE_URL
          value: postgresql://postgres:qShhYgujF3MbMP@peerprep-postgres:5432/peerprep
        - name: PSQL_DATABASE
          value: peerprep
        - name: PSQL_USER
          value: postgres
        - name: PSQL_PASSWORD
          value: qShhYgujF3MbMP
        - name: PSQL_HOST
          value: peerprep-postgres
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001

