apiVersion: v1
kind: Service
metadata:
  name: peerprep-session
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  selector:
    app: peerprep-session
  ports:
  - protocol: TCP
    name: port-8250
    port: 8250
  - protocol: TCP
    name: port-8251
    port: 8251
  type: LoadBalancer
  loadBalancerIP: 35.213.173.19

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deployment
spec:
  selector:
    matchLabels:
      app: peerprep-session
  template:
    metadata:
      labels:
        app: peerprep-session
    spec:
      containers:
      - name: peerprep-session
        image: deployment87/dply87:peerprep-session
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8250
        - containerPort: 8251
