apiVersion: v1
kind: Service
metadata:
  name: peerprep-queue
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  selector:
    app: peerprep-queue
  ports:
  - protocol: TCP
    port: 8002
  type: LoadBalancer
  loadBalancerIP: 35.213.173.19

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  selector:
    matchLabels:
      app: peerprep-queue
  template:
    metadata:
      labels:
        app: peerprep-queue
    spec:
      containers:
      - name: peerprep-question
        image: deployment87/dply87:peerprep-queue
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
