export enum Language {
    c = "C",
    cplusplus = "C++",
    csharp = "C#",
    java = "Java",
    javascript = "JavaScript",
    python = "Python",
    python3 = "Python3",
    typescript = "TypeScript",
    golang = "Go",
    swift = "Swift",
    php = "PHP",
    ruby = "Ruby",
    rust = "Rust",
    kotlin = "Kotlin",
    scala = "Scala",
}
