apiVersion: v1
kind: Service
metadata:
  name: peerprep-question
spec:
  selector:
    app: peerprep-question
  ports:
  - protocol: TCP
    port: 8000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
spec:
  selector:
    matchLabels:
      app: peerprep-question
  template:
    metadata:
      labels:
        app: peerprep-question
    spec:
      containers:
      - name: peerprep-question
        image: deployment87/dply87:peerprep-question
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
