apiVersion: v1
kind: Service
metadata:
  name: peerprep-frontend
spec:
  selector:
    app: peerprep-frontend
  ports:
  - protocol: TCP
    port: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: peerprep-frontend
  template:
    metadata:
      labels:
        app: peerprep-frontend
    spec:
      containers:
      - name: peerprep-frontend
        image: deployment87/dply87:peerprep-frontend
        env:
        - name: NEXTAUTH_URL
          value: http://frontend-service:3000
        - name: NEXT_PUBLIC_USER_SERVICE
          value: http://user-service:8001
        - name: NEXT_PUBLIC_QUESTION_SERVICE
          value: http://question-service:8000
        - name: NEXT_PUBLIC_WS_URL
          value: ws://question-service:8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
