# Use the official Node.js 18 image as a parent image
FROM node:18

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install all dependencies in the package.json
RUN yarn install

# Copy all files from your host to your image filesystem at /app
COPY . .
COPY .env.dev .env

# Install prisma
RUN npx prisma generate

# Informs Docker that the container listens on the specified network ports at runtime.
EXPOSE 8001

# Provides defaults for an executing container
CMD ["yarn" ,"start:prod"]
