# Use the official Node.js 16 image as a parent image
FROM node:16

# Set the working directory in the container to /app
WORKDIR /app

# Copy all files from your host to your image filesystem at /app
COPY . .

# Install all dependencies in the package.json
RUN yarn install

RUN npx prisma generate

# Informs Docker that the container listens on the specified network ports at runtime.
EXPOSE 8000
EXPOSE 5432

# Provides defaults for an executing container
CMD ["yarn", "start"]
